// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfHYRfp7gDsoZWcYaViu4eLLwiQHrRlQs',
    appId: '1:1094960140109:web:e3f8bf298e8b23ae377104',
    messagingSenderId: '1094960140109',
    projectId: 'calisteniapp-v2',
    authDomain: 'calisteniapp-v2.firebaseapp.com',
    storageBucket: 'calisteniapp-v2.firebasestorage.app',
    measurementId: 'G-8VD0NYT2N3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiz26-SiPoaTI5IUDWbc-KU0x1WedpLv0',
    appId: '1:1094960140109:android:2d277db03b2c68d9377104',
    messagingSenderId: '1094960140109',
    projectId: 'calisteniapp-v2',
    storageBucket: 'calisteniapp-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK6o9kJm-63fGyinQF_M9rQzRrxoRPaXM',
    appId: '1:1094960140109:ios:3b7408aa304d1f61377104',
    messagingSenderId: '1094960140109',
    projectId: 'calisteniapp-v2',
    storageBucket: 'calisteniapp-v2.firebasestorage.app',
    iosBundleId: 'com.example.calisteniappV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK6o9kJm-63fGyinQF_M9rQzRrxoRPaXM',
    appId: '1:1094960140109:ios:3b7408aa304d1f61377104',
    messagingSenderId: '1094960140109',
    projectId: 'calisteniapp-v2',
    storageBucket: 'calisteniapp-v2.firebasestorage.app',
    iosBundleId: 'com.example.calisteniappV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfHYRfp7gDsoZWcYaViu4eLLwiQHrRlQs',
    appId: '1:1094960140109:web:dd273cba3351400e377104',
    messagingSenderId: '1094960140109',
    projectId: 'calisteniapp-v2',
    authDomain: 'calisteniapp-v2.firebaseapp.com',
    storageBucket: 'calisteniapp-v2.firebasestorage.app',
    measurementId: 'G-DK90BYWZFB',
  );
}
